### PR TITLE
Add php 8.3 and drop php 8.0

### PR DESCRIPTION
**Pull request by Xerkus**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### CODE REVIEW

**Comment by Xerkus** [comment]
Blocked by https://github.com/laminas/laminas-container-config-test/pull/26

**Comment by Ocramius** [comment]
@Xerkus given #27, I'd suggest ending efforts here and archiving.

**Comment by Xerkus** [comment]
@Ocramius my plan was to get that merged and released, then merge this and release then archive.
Considering packagist "install" stats either way works.

**Comment by Ocramius** [comment]
@Xerkus upstream blocker fixed: just re-run here and 🚢 -ing

**Pull request merged**
